// <auto-generated />
namespace redfoodie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenameReviewtoReviewText : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameReviewtoReviewText));
        
        string IMigrationMetadata.Id
        {
            get { return "201612111103452_Rename Review to ReviewText"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
